### ISSUE TITLE
[Bug]: CraftTweaker Incompatibility

### ISSUE THREAD

**Issue by TQCnoARosto** [Fuzss/visualworkbench#31]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.4

### Notes (Required)

I modified a crafting recipe with the crafttweaker mod.

If i place the ingredients inside the crafting table in the correct position and close the crafting table gui everything is fine, but when i reopen it, the recipe output disappears.
![CraftingOk](https://user-images.githubusercontent.com/43849125/228286825-032d07ff-bd66-4f4d-aac8-3972404a7551.png)
![CraftingNotOk](https://user-images.githubusercontent.com/43849125/228286837-d1a7b446-d01a-4566-806a-0db965b39771.png)

A temporary solution is to remove and replace an ingredient in the recipe and the output reappears.

**Comment by Darkosto** [comment]
It seems like this issue is caused by using a custom crafting container that is meant to pass method calls to a delegate container: https://github.com/Fuzss/visualworkbench/blob/main/1.20/Common/src/main/java/fuzs/visualworkbench/world/inventory/ForwardingCraftingContainer.java#L13C72-L13C72

Visual Workbench's crafting container is not the container that CraftTweaker or other mods are expecting: https://github.com/jaredlll08/RecipeStages/blob/a347ca2a8138d9ab44b73ac7e45a90f51fa28f2b/src/main/java/com/blamejared/recipestages/recipes/IStagedRecipe.java#L87

This could potentially be solved by making the container extend `TransientCraftingContainer` instead of just `CraftingContainer`

**Comment by Fuzss** [comment]
This has only been fixed for 1.20.4+ yet.

**Comment by Leocide** [comment]
1.20.1 still not playable with visual workbench
