### ISSUE TITLE
[Bug]: Visual Workbench does not work with all Variant Crafting Tables' workbenches

### ISSUE THREAD

**Issue by Numerosityy** [Fuzss/visualworkbench#35]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.4

### Notes (Required)

Current behavior:
For newer crafting tables added to Variant Crafting Tables, the Visual Workbench mod isn't compatible.
Steps to reproduce:
Place a recently added crafting table from the mod Variant Crafting Tables
Add items inside crafting table
Expected: Should show items visually, just like the other work benches.

Idk why this is an issue, unless you have a unblocked list. Would recommend just automatically adding compatibility based on tags like #charm:crafting_table or #forge:workbench, if possible

**Comment by Fuzss** [comment]
Visual Workbench even works with crafting tables added by other mods. Support has to be manually enabled per block though. Many modded crafting tables are supported by default, those that are not can be added to a custom config file found at .minecraft/config/visual_workbench.json (not accessible from in-game). If you add a crafting table yourself and it doesn't work it is likely just not possible to be supported by this mod.

Supporting tags is not possible since those are resolved on a per world basis, while block entity registration happens during the game's launch (this is when support for the different crafting tables is enabled).

**Comment by Fuzss** [comment]
If you post the ids for the newer crafting tables that currently don't work by default here I'll include them in the next release. Apart from that this isn't a valid issue.

**Comment by Numerosityy** [comment]
Fair enough, ig if there's nothing that can be done about it to prevent the issue then it just needs to keep being updated. Will add a list of the unsupported blocks here. Love your mod btw, and I appreciate your quick response!
