### ISSUE TITLE
[Suggestion]: Autocrafting? (hear me out)

### ISSUE THREAD

**Issue by Aceplante2** [Fuzss/visualworkbench#37]
### Suggestion (Required)

Since crafting tables can now store items, how about a configurable option for it to automatically craft as well? If there is a valid recipe in the left, why not have it output the result on the right? A rate of 1 craft per second seems good as a default, but would hopefully be configurable.

For example, the easiest way to use this feature would be for compacting blocks such as bonemeal or wheat, but could maybe be used for more complex recipes if you input items in the proper order. Also, if they are not already, crafting tables would now work with hoppers too?

**Comment by Fuzss** [comment]
I thought about this a lot already and I want to have auto-crafting, but as a separate mod with a separate crafting table like block (with other capabilities too). Ilmango has a video about auto-crafting which is the most ideal implementation I believe. 
Hoppers do not work with Visual Workbench since auto-crafting isn’t a thing anyways.
